@startuml

skinparam state {
  FontName "PT Sans"
}

[*] --> ReadyForService
ReadyForService --> [*] 

ReadyForService -left-> Service
Service --> ReadyForService

ReadyForService -right-> OutOfService
OutOfService --> ReadyForService 

/'
    ReadyForService --> Idle
    Idle --> ReadyForService 
    Idle --> [*]
'/

@enduml
