
echo:
    title: English is one of the most widely spoken languages in the world
    message: Approximately 360 to 400 million people speak it natively, while another 470 million to more than one billion claim English as a second language.

spring:
    devtools:
        restart:
            trigger-file: ".reboot"